# Generated by Django 3.0.5 on 2021-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Years', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Case_Number',
            new_name='Cat',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Case_Numbers',
            new_name='Cats',
        ),
    ]
