# Generated by Django 3.0.5 on 2021-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0002_auto_20210414_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('casetype', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('caseNo', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('year_value', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('InternelCategorys', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('InternelCustom', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('dprtmnt', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('commis', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('bodies', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Boards', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('post', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Advertisements_year', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cat', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('copy', models.FileField(upload_to='uploads/')),
                ('prayer', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('issue', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('law', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('nextdate', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lastorder', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
