# Generated by Django 3.0.5 on 2021-04-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='copy',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lastorder',
            field=models.FileField(upload_to='media'),
        ),
    ]
