# Generated by Django 3.0.5 on 2021-04-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0004_auto_20210415_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='copy',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lastorder',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
