# Generated by Django 2.2.1 on 2021-04-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0006_auto_20210416_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='copy',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lastorder',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
