# Generated by Django 3.0.5 on 2021-04-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0008_othersdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othersdoc',
            name='userid',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='court.userinfo'),
        ),
    ]
