# Generated by Django 3.0.5 on 2021-04-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0009_auto_20210418_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersdoc',
            name='copy',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othersdoc',
            name='lastorder',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='othersdoc',
            name='othersodcs',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='othersdoc',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.userinfo'),
        ),
    ]
